### ISSUE TITLE
System names

### ISSUE THREAD

**Issue by ondrae** [18F/all_sorns#30]
Currently, our system names look like 
> ["Department of Homeland Security (DHS)/United States Secret Service (USSS)-001 Criminal Investigation Information System of Records."]

- We are missing system names for 1997 out of 6467 SORNs.
- We know different agencies publish SORNs differently

### Todo
- [ ] Separate system name and system number
- [ ] Don't include agency name
- [ ] Increase the number of system names we have

**Comment by lauraGgit** [comment]
RE: "Separate system name and system number"
system_name ~ '\d+—?\d+' yields 1338 sorns

while system_name ~ '\d+'; yields 1463
